Update service scripts for Coordinator, Provisioner, ReportBot

diff --git a/roles/arch3_master/templates/Provisioner.j2 b/roles/arch3_master/templates/Provisioner.j2
--- a/roles/arch3_master/templates/Provisioner.j2
+++ b/roles/arch3_master/templates/Provisioner.j2
@@ -1,4 +1,60 @@
 #! /bin/bash
 
+#nohup java -cp /home/ubuntu/arch3/pancancer.jar info.pancancer.arch3.containerProvisioner.ContainerProvisionerThreads  $@ &> /home/$USER/arch3/logs/provisioner.out
+SERVICE_NAME=Provisioner
+LOG_FILE="/var/log/arch3/$SERVICE_NAME.log"
+PID_FILE="/var/run/arch3_$SERVICE_NAME.pid"
+CLASS_NAME=info.pancancer.arch3.containerProvisioner.ContainerProvisionerThreads
+JAR_FILE=/home/ubuntu/arch3/pancancer.jar
+CONFIG_PATH=/etc/arch3/masterConfig.ini
 
-nohup java -cp /home/ubuntu/arch3/pancancer.jar info.pancancer.arch3.containerProvisioner.ContainerProvisionerThreads  $@ &> provisioner.out
+case "$1" in
+  start)
+      echo "Starting up $SERVICE_NAME..."
+      sudo start-stop-daemon --start -b -m --pidfile $PID_FILE --exec /usr/bin/java -- -cp $JAR_FILE $CLASS_NAME --endless --config $CONFIG_PATH
+      cat $PID_FILE
+    ;;
+  stop)
+     echo "Stopping $SERVICE_NAME..."
+     set -e
+     sudo start-stop-daemon --stop --signal KILL -m --pidfile $PID_FILE --exec /usr/bin/java -- -cp $JAR_FILE $CLASS_NAME --endless --config $CONFIG_PATH
+     sudo rm -f $PID_FILE
+     set +e
+    ;;
+  status)
+    sudo start-stop-daemon --status --pidfile $PID_FILE
+    PROC_STATUS=$?
+    echo "Status code: $PROC_STATUS"
+    case "$PROC_STATUS" in
+      0)
+        echo "$SERVICE_NAME is running, with PID: $(cat $PID_FILE)"
+        ;;
+      1)
+        echo "$SERVICE_NAME is not running, but PID file may exist: $PID_FILE"
+        cat $PID_FILE
+        ;;
+      3)
+        echo "$SERVICE_NAME is not running."
+        ;;
+      4)
+        echo "Unable to determine status of $SERVICE_NAME!"
+        ;;
+    esac
+    exit $PROC_STATUS
+    ;;
+  restart)
+     echo "Restarting $SERVICE_NAME..."
+     set -e
+     sudo start-stop-daemon --stop --signal KILL --pidfile $PID_FILE --exec /usr/bin/java -- -cp $JAR_FILE $CLASS_NAME --endless --config $CONFIG_PATH
+     sudo rm -f $PID_FILE
+     sudo start-stop-daemon --start -b -m --pidfile $PID_FILE --exec /usr/bin/java -- -cp $JAR_FILE $CLASS_NAME --endless --config $CONFIG_PATH
+     set +e
+     cat $PID_FILE
+    ;;
+  *)
+    echo $"Usage: $0 {start|stop|status|restart}"
+    exit 1
+    ;;
+esac
+
+exit 0
